import type { Metadata } from "next";
import Link from "next/link";
import { Geist, Geist_Mono } from "next/font/google";
import Chat from "./chat/chatComponent";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <div className="navbar">
          <div className="container">
            <div className="navbar-inner">
              <Link href="/articles" className="navbar-item">Articles</Link>
              <Link href="/articles/new" className="navbar-item">Créer un article</Link>
            </div>
          </div>
        </div>
        {children}
        <Chat/>
        <div className="footer">
          @Copyright 2025 - Julien.R
        </div>
      </body>
    </html>
  );
}
